# Generated by Django 2.2 on 2020-08-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_app', '0002_cocktail_drink_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='ppo',
            field=models.FloatField(),
        ),
    ]
